---
dataset_name: Devign
model_name: hugging_face_sequence_classification_microsoft_codebert-base
epoch: 10
log_level: INFO
cache_transforms: device
learning_rate: 4.636375729501466e-05
dataset_kwargs:
  max_len: 510
model_kwargs:
  pretrained: true
  frozen_modules:
    names:
      - roberta.embeddings
      - roberta.encoder.layer.0
      - roberta.encoder.layer.1
      - roberta.encoder.layer.2
      - roberta.encoder.layer.3
      - roberta.encoder.layer.4
      - roberta.encoder.layer.5
      - roberta.encoder.layer.6
      - roberta.encoder.layer.7
      - roberta.encoder.layer.8
      - roberta.encoder.layer.9
      - roberta.encoder.layer.10
