---
dataset_name: ImageNet
model_name: efficientnet_b3
optimizer_name: SGD
epoch: 50
pretrained: true
optimizer_name: SGD
cache_transforms: false
use_amp: true
log_level: INFO
batch_size: 128
learning_rate: 0.01
learning_rate_scheduler: CosineAnnealingLR
...
