---
dataset_name: IMDB
model_name: hugging_face_sequence_classification_bert-base-cased
optimizer_name: SGD
epoch: 10
use_amp: true
learning_rate_scheduler: CosineAnnealingLR
learning_rate: 0.01
log_level: INFO
cache_transforms: true
dataset_kwargs:
  tokenizer:
    type: hugging_face
    name: bert-base-cased
  max_len: 300
...
