---
dataset_name: imdb
model_name: hugging_face_sequence_classification_bert-base-cased
optimizer_name: SGD
epoch: 10
use_amp: true
learning_rate_scheduler_name: CosineAnnealingLR
learning_rate: 0.01
log_level: INFO
cache_transforms: device
dataset_kwargs:
  input_max_len: 300
