---
dataset_name: IMDB
model_name: TransformerClassificationModel
optimizer_name: SGD
epoch: 10
use_amp: true
learning_rate_scheduler: CosineAnnealingLR
learning_rate: 0.01
log_level: INFO
cache_transforms: true
dataset_kwargs:
  dataset_type: text
  max_len: 300
  tokenizer:
    type: spacy
model_kwargs:
  max_len: 300
  word_vector_name: glove.6B.100d
  num_encoder_layer: 2
  d_model: 100
  nhead: 5
...
