---
dataset_name: multi_nli
model_name: hugging_face_seq2seq_lm_t5-large
optimizer_name: SGD
epoch: 10
use_amp: true
learning_rate_scheduler: CosineAnnealingLR
learning_rate: 0.004
log_level: INFO
cache_transforms: true
pretrained: true
dataset_kwargs:
  max_len: 300
  val_split: validation_matched
