---
dataset_name: multi_nli
model_name: TransformerClassificationModel
optimizer_name: SGD
epoch: 1
use_amp: true
learning_rate: 0.004
learning_rate_scheduler: CosineAnnealingLR
log_level: INFO
cache_transforms: cuda
dataset_kwargs:
  val_split: validation_matched
model_kwargs:
  max_len: 300
  word_vector_name: glove.6B.100d
  num_encoder_layer: 5
  nhead: 10
  d_model: 100
tracked_word_number: 200
use_IF: false
use_GD: false
use_GC: false
use_relatIF: false
...
