---
dataset_name: ogbn-products
model_name: TwoGATCN
epoch: 100
batch_size: 100
use_amp: false
log_level: INFO
learning_rate: 0.1
weight_decay: 0.001
cache_transforms: cpu
dataloader_kwargs:
  batch_number: 1000
  num_neighbor: 10
